services:
  - type: web
    name: arduino-scanner-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9
      - key: LICENSE_KEYS
        sync: false # This ensures the value is not overwritten on redeploy
